# Generated by Django 6.0.3 on 2026-04-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
    ]
