# Generated by Django 6.0.3 on 2026-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=100),
        ),
    ]
