# Generated by Django 6.0.3 on 2026-04-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('job_type', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
