# Generated by Django 6.0.3 on 2026-04-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Add_Job',
        ),
    ]
