# Generated by Django 6.0.4 on 2026-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_job_add_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='add_job',
            name='skills',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='add_job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
